name: nestafar
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shimmer: ^3.0.0
  shared_preferences: ^2.1.0
  device_info_plus: ^10.1.0
  package_info_plus: ^4.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/restaurant/
    - assets/images/menu/
    - assets/mock/
    - assets/